steps:
  test:
    image: python:3.12.0-alpine3.18
    secrets: [django_secret_key]
    commands:
      - apk add --update alpine-sdk libffi-dev
      - pip install -r requirements.txt
      - export "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY"
      - export "DEBUG=true"
      - export "DEPLOYED=false"
      - export "FRONTEND_DOMAIN=https://dev.realityhack.world"
      - export "KEYCLOAK_SERVER_URL=https://dev-api.realityhack.world:8443/"
      - export "KEYCLOAK_REALM=master"
      - export "KEYCLOAK_CLIENT_ID=123456"
      - export "KEYCLOAK_CLIENT_SECRET_KEY=123456"
      - ./test
