ARG PYTHON_VERSION=3.10-slim-bullseye


FROM python:${PYTHON_VERSION} as django-builder

# COPY --from=keycloak-builder /opt/keycloak/ /opt/keycloak/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies.
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /code

WORKDIR /code
RUN mkdir -p /code/logs && touch /code/logs/request.log
RUN pip install --upgrade pip setuptools wheel
RUN pip install poetry
RUN poetry config virtualenvs.create false
COPY pyproject.toml poetry.lock /code/
RUN poetry install --only main --no-root --no-interaction
COPY . /code

RUN python manage.py collectstatic --noinput

EXPOSE 8000

# CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "event_server.asgi:application"]
