# fly.toml app configuration file generated for realityhack-world-backend-production on 2024-10-16T18:31:55-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'realityhack-world-backend-production'
primary_region = 'ewr'
console_command = '/code/manage.py shell'

[build]
  dockerfile = 'Dockerfile.fly'

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[processes]
  app = 'daphne -b 0.0.0.0 -p 8000 event_server.asgi:application'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
