#!/usr/bin/env sh

if [ ! -d /home/django/keycloak ]; then
    cd /home/django
    if [ -f /django_project/.env ]; then
        export $(echo $(cat /home/django/django_project/.env | sed 's/#.*//g'| xargs) | envsubst)
    fi
    apt-get update
    apt-get install openjdk-17-jre -y
    wget https://github.com/keycloak/keycloak/releases/download/22.0.4/keycloak-22.0.4.tar.gz
    tar -xvzf keycloak-22.0.4.tar.gz
    rm keycloak-22.0.4.tar.gz
    mv keycloak-22.0.4 keycloak
    cd keycloak
    /home/django/keycloak/bin/kc.sh build
    PGPASSWORD=$DJANGO_POSTGRESS_PASS sudo -u postgres psql -c 'create database keycloak;'
    cd /home/django/django_project
fi

ufw allow 22
ufw allow 8443

pip3 install -r requirements.txt
python3 manage.py migrate
python3 manage.py collectstatic --noinput
cp deploy/etc/systemd/system/daphne.service /etc/systemd/system/daphne.service
cp deploy/etc/systemd/system/keycloak.service /etc/systemd/system/keycloak.service
cp deploy/etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
chown -R django /home/django
chown -R /etc/letsencrypt/live
chown -R /etc/letsencrypt/archive
systemctl daemon-reload
systemctl enable daphne
systemctl start daphne
systemctl enable nginx
systemctl start nginx
systemctl enable keycloak
systemctl start keycloak
tail -f /var/log/syslog | grep daphne
