# Generated by Django 4.2 on 2023-06-07 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='role',
            new_name='roles',
        ),
    ]
