# Generated by Django 4.2.2 on 2023-11-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='communications_platform_username',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
