# Generated by Django 4.2.2 on 2023-07-13 00:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('event_year', models.IntegerField(default=2024)),
                ('skill_proficiencies', models.JSONField(default=dict)),
                ('portfolio', models.URLField()),
                ('resume', models.URLField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary'), ('D', 'D')], default='D', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('D', 'Declined'), ('I', 'Accepted, In-Person')], default=None, max_length=1, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
