# Generated by Django 4.2 on 2023-04-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'attendees'},
        ),
        migrations.AlterModelOptions(
            name='skillproficiency',
            options={'verbose_name': 'skill proficiencies'},
        ),
        migrations.AlterField(
            model_name='skillproficiency',
            name='proficiency',
            field=models.CharField(choices=[('N', 'Novice'), ('C', 'Competent'), ('P', 'Proficient'), ('M', 'Master')], default='N', max_length=1),
        ),
    ]
