# Generated by Django 4.2 on 2023-06-26 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_attendee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaredevice',
            name='checked_out_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
