# Generated by Django 4.2.2 on 2023-07-13 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary'), ('D', 'Decline')], default='D', max_length=1),
        ),
    ]
