# Generated by Django 4.2 on 2023-06-25 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_rename_skills_attendee_skill_proficiencies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='skill_proficiencies',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='auxiliary_requested',
        ),
    ]
