# Generated by Django 4.2 on 2023-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_alter_attendee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['last_name', 'first_name'], name='infrastruct_last_na_029e47_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['first_name'], name='infrastruct_first_n_5c1abd_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['last_name'], name='infrastruct_last_na_46c1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['username'], name='infrastruct_usernam_0bcdcc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['email'], name='infrastruct_email_a899f3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['is_staff'], name='infrastruct_is_staf_9a7229_idx'),
        ),
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['metadata'], name='infrastruct_metadat_bc35e8_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='infrastruct_name_661d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['table'], name='infrastruct_table_i_c8f6ee_idx'),
        ),
    ]
