# Generated by Django 4.2.2 on 2023-12-20 18:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_alter_application_nullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender_identity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Cisgender female'), ('B', 'Cisgender male'), ('C', 'Transgender female'), ('D', 'Transgender male'), ('E', 'Gender non-conforming, non-binary, or gender queer'), ('F', 'Two-spirit'), ('G', 'I prefer not to say'), ('O', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_participation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', '2016'), ('B', '2017'), ('C', '2018'), ('D', '2019'), ('E', '2020'), ('F', '2022'), ('G', '2023')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='race_ethnic_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Asian, Asian American, or of Asian descent'), ('B', 'Black, African American, or of African descent'), ('C', 'Hispanic, Latino, Latina, Latinx, or of Latinx or Spanish-speaking descent'), ('D', 'Middle Eastern, North African, or of North African descent'), ('E', 'Native American, American Indian, Alaska Native, or Indigenous'), ('F', 'Pacific Islander or Native Hawaiian'), ('G', 'White or of European descent'), ('H', 'Multi-racial or multi-ethnic'), ('I', 'I prefer not to say'), ('O', 'Other')], max_length=20),
        ),
    ]
