# Generated by Django 4.2.2 on 2023-10-28 22:36

import uuid

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_uploadedfile_and_application_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_materials', models.URLField(blank=True, null=True)),
                ('recommended_for', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Designer'), ('D', 'Developer'), ('S', 'Specialist')], max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.ManyToManyField(related_name='workshop_hardware', to='infrastructure.hardware')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_location', to='infrastructure.location')),
                ('skills', models.ManyToManyField(related_name='workshop_skills', to='infrastructure.skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participation', models.CharField(choices=[('R', "RSVP'd"), ('C', 'Confirmed'), ('I', 'Instructor'), ('V', 'Volunteer')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_attendee_attendee', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_attendee_workshop', to='infrastructure.workshop')),
            ],
        ),
    ]
