# Generated by Django 4.2.2 on 2024-01-04 18:56

import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_alter_application_gender_identity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendee',
            name='infrastruct_metadat_bc35e8_idx',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='skillproficiency',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='rsvp_email_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='additional_accommodations',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='agree_to_liability_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='agree_to_media_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='agree_to_rules_code_of_conduct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='app_in_store',
            field=models.CharField(help_text='Do you already have an AR or VR app in any store? And if so, which store(s)?', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='ar_vr_ap_in_store',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='authentication_id',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='checked_in_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='communications_platform_username',
            field=models.CharField(help_text='I.e., a Discord username', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='currently_build_for_xr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='currently_use_xr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='dietary_allergies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Nut allergy'), ('2', 'Shellfish allergy'), ('3', 'Dairy allergy'), ('4', 'Soy allergy'), ('5', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='dietary_allergies_other',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Vegetarian'), ('2', 'Vegan'), ('3', 'Gluten free'), ('4', 'Halal'), ('5', 'Lactose Intolerant'), ('6', 'Kosher'), ('7', 'Other')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='dietary_restrictions_other',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='emergency_contact_email',
            field=models.EmailField(default='N/A', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='emergency_contact_name',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='emergency_contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='N/A', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='emergency_contact_relationship',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='initial_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='non_xr_talents',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='parental_consent_form_signed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='participation_class',
            field=models.CharField(choices=[('P', 'Participant'), ('M', 'Mentor'), ('J', 'Judge'), ('S', 'Sponsor'), ('V', 'Volunteer'), ('O', 'Organizer')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='attendee',
            name='participation_role',
            field=models.CharField(choices=[('A', 'Digital Designer'), ('D', 'Developer'), ('S', 'Domain or other Specialized Skill Expert'), ('P', 'Project Manager')], default='S', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='personal_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='N/A', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='profile_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee_profile_image_uploaded_file', to='infrastructure.uploadedfile'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='reality_hack_project_to_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='shirt_size',
            field=models.CharField(choices=[('1', 'XS'), ('2', 'S'), ('3', 'M'), ('4', 'L'), ('5', 'XL'), ('6', 'XXL')], default='3', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='special_track_future_constructors_interest',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='special_track_snapdragon_spaces_interest',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='sponsor_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('R', "RSVP'd"), ('A', 'Arrived'), ('C', 'Canceled')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='attendee',
            name='under_18_by_date',
            field=models.BooleanField(help_text='Will you be under 18 on January 25, 2024', null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_letter_of_invitation_required',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_address',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_citizenship',
            field=models.CharField(choices=[('AW', 'Aruba'), ('AF', 'Afghanistan'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AS', 'American Samoa'), ('AQ', 'Antarctica'), ('TF', 'French Southern Territories'), ('AG', 'Antigua and Barbuda'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BI', 'Burundi'), ('BE', 'Belgium'), ('BJ', 'Benin'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BF', 'Burkina Faso'), ('BD', 'Bangladesh'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BS', 'Bahamas'), ('BA', 'Bosnia and Herzegovina'), ('BL', 'Saint Barthélemy'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('BM', 'Bermuda'), ('BO', 'Bolivia, Plurinational State of'), ('BR', 'Brazil'), ('BB', 'Barbados'), ('BN', 'Brunei Darussalam'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('CF', 'Central African Republic'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CH', 'Switzerland'), ('CL', 'Chile'), ('CN', 'China'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CD', 'Congo, The Democratic Republic of the'), ('CG', 'Congo'), ('CK', 'Cook Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CV', 'Cabo Verde'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CX', 'Christmas Island'), ('KY', 'Cayman Islands'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('EH', 'Western Sahara'), ('ES', 'Spain'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FR', 'France'), ('FO', 'Faroe Islands'), ('FM', 'Micronesia, Federated States of'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GE', 'Georgia'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GM', 'Gambia'), ('GW', 'Guinea-Bissau'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GD', 'Grenada'), ('GL', 'Greenland'), ('GT', 'Guatemala'), ('GF', 'French Guiana'), ('GU', 'Guam'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IE', 'Ireland'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IS', 'Iceland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KN', 'Saint Kitts and Nevis'), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('MO', 'Macao'), ('MF', 'Saint Martin (French part)'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Moldova, Republic of'), ('MG', 'Madagascar'), ('MV', 'Maldives'), ('MX', 'Mexico'), ('MH', 'Marshall Islands'), ('MK', 'North Macedonia'), ('ML', 'Mali'), ('MT', 'Malta'), ('MM', 'Myanmar'), ('ME', 'Montenegro'), ('MN', 'Mongolia'), ('MP', 'Northern Mariana Islands'), ('MZ', 'Mozambique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MQ', 'Martinique'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('YT', 'Mayotte'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NU', 'Niue'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PA', 'Panama'), ('PN', 'Pitcairn'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PW', 'Palau'), ('PG', 'Papua New Guinea'), ('PL', 'Poland'), ('PR', 'Puerto Rico'), ('KP', "Korea, Democratic People's Republic of"), ('PT', 'Portugal'), ('PY', 'Paraguay'), ('PS', 'Palestine, State of'), ('PF', 'French Polynesia'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SD', 'Sudan'), ('SN', 'Senegal'), ('SG', 'Singapore'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('SJ', 'Svalbard and Jan Mayen'), ('SB', 'Solomon Islands'), ('SL', 'Sierra Leone'), ('SV', 'El Salvador'), ('SM', 'San Marino'), ('SO', 'Somalia'), ('PM', 'Saint Pierre and Miquelon'), ('RS', 'Serbia'), ('SS', 'South Sudan'), ('ST', 'Sao Tome and Principe'), ('SR', 'Suriname'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SE', 'Sweden'), ('SZ', 'Eswatini'), ('SX', 'Sint Maarten (Dutch part)'), ('SC', 'Seychelles'), ('SY', 'Syrian Arab Republic'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TM', 'Turkmenistan'), ('TL', 'Timor-Leste'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TV', 'Tuvalu'), ('TW', 'Taiwan, Province of China'), ('TZ', 'Tanzania, United Republic of'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('US', 'United States'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City State)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('VN', 'Viet Nam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_document_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_is_required',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='us_visa_support_national_identification_document_type',
            field=models.CharField(choices=[('P', 'Passport'), ('N', 'National/State/Municipal ID')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='is_xr_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_resume_uploaded_file', to='infrastructure.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.team'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.location'),
        ),
        migrations.AlterField(
            model_name='team',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.table'),
        ),
    ]
