# Generated by Django 4.2.2 on 2024-01-13 01:53

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_remove_attendee_infrastruct_metadat_bc35e8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMentorHelpRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Acknowledged'), ('E', 'En Route'), ('F', 'Resolved')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical mentor help request',
                'verbose_name_plural': 'historical mentor help requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LightHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('announcement_pending', models.CharField(choices=[('S', 'Send'), ('A', 'Alert'), ('F', 'Resolve')], default='F', max_length=1)),
                ('mentor_requested', models.CharField(choices=[('R', 'Requested'), ('A', 'Acknowledged'), ('E', 'En Route'), ('F', 'Resolved')], default='F', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.table')),
            ],
        ),
        migrations.CreateModel(
            name='MentorHelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('status', models.CharField(choices=[('R', 'Requested'), ('A', 'Acknowledged'), ('E', 'En Route'), ('F', 'Resolved')], default='R', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='authentication_roles_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HelpDesk',
        ),
        migrations.AddField(
            model_name='mentorhelprequest',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_help_request_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorhelprequest',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_help_request_reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorhelprequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.team'),
        ),
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='mentor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='reporter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.team'),
        ),
    ]
