# Generated by Django 4.2.2 on 2023-10-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_workshop_workshopattendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
