# Generated by Django 4.2.2 on 2023-11-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_remove_application_emergency_contact_email_and_more'),
        ('infrastructure', '0008_workshop_name'),
    ]

    operations = [
    ]
