# Generated by Django 4.2.2 on 2024-01-13 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_historicalmentorhelprequest_lighthouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='guardian_of',
            field=models.ManyToManyField(related_name='attendee_guardian_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendee',
            name='sponsor_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee_sponsor_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='participation_class',
            field=models.CharField(choices=[('P', 'Participant'), ('M', 'Mentor'), ('J', 'Judge'), ('S', 'Sponsor'), ('V', 'Volunteer'), ('O', 'Organizer'), ('G', 'Guardian'), ('E', 'Media')], default='P', max_length=1),
        ),
    ]
