# Generated by Django 4.2.2 on 2024-01-13 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_attendee_guardian_of_attendee_sponsor_handler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='guardian_of',
            field=models.ManyToManyField(blank=True, related_name='attendee_guardian_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='team_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='hardware',
            field=models.ManyToManyField(blank=True, related_name='workshop_hardware', to='infrastructure.hardware'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='workshop_skills', to='infrastructure.skill'),
        ),
    ]
