# Generated by Django 4.2.2 on 2024-01-15 00:50

import uuid

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0010_alter_attendee_guardian_of_alter_team_attendees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="tags",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("VR", "VR Hardware"), ("AR", "AR Hardware")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HardwareRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                            ("C", "Checked out"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hardware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.hardware",
                    ),
                ),
                (
                    "hardware_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.hardwaredevice",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="infrastructure.team",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="hardwaredevice",
            name="checked_out_to",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="infrastructure.hardwarerequest",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhardwaredevice",
            name="checked_out_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.hardwarerequest",
            ),
        ),
    ]
