# Generated by Django 4.2.2 on 2024-01-16 05:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_historicalmentorhelprequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='hardware_hack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='intended_hardware_hack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='intended_tracks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('F', 'Future Constructors'), ('L', 'Learning'), ('W', 'Work'), ('H', 'Health and Well-Being'), ('S', 'Smart Cities and Sustainability'), ('C', 'Community Hacks')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='prefers_destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='hardware',
            name='relates_to_destiny_hardware',
            field=models.CharField(choices=[('H', 'Hardware Hack'), ('M', 'Meta'), ('Q', 'Snapdragon Spaces'), ('X', 'XREAL'), ('S', 'Snap Spectacles')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='track',
            field=models.CharField(choices=[('F', 'Future Constructors'), ('L', 'Learning'), ('W', 'Work'), ('H', 'Health and Well-Being'), ('S', 'Smart Cities and Sustainability'), ('C', 'Community Hacks')], max_length=1, null=True),
        ),
    ]
