# Generated by Django 4.2.2 on 2024-01-16 19:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0013_attendee_hardware_hack_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardware",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hardware_image_uploaded_file",
                to="infrastructure.uploadedfile",
            ),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="tags",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("AC", "Accessory"),
                    ("SE", "Sensor"),
                    ("VR", "Virtual Reality"),
                    ("AR", "Augmented Reality"),
                    ("MR", "Mixed Reality"),
                    ("CO", "Computer"),
                    ("HA", "Haptics"),
                    ("CA", "Camera"),
                    ("TA", "Tablet"),
                    ("HD", "Holographic Display"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
