# Generated by Django 4.2.2 on 2024-01-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_alter_hardware_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='N/A', max_length=1000),
            preserve_default=False,
        ),
    ]
