# Generated by Django 4.2.2 on 2024-01-23 19:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinyTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track', models.CharField(choices=[('F', 'Future Constructors'), ('L', 'Learning'), ('W', 'Work'), ('H', 'Health and Well-Being'), ('S', 'Smart Cities and Sustainability'), ('C', 'Community Hacks')], max_length=1, null=True)),
                ('round', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='hardware_hack',
        ),
        migrations.AddField(
            model_name='team',
            name='hardware_hack',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DestinyTeamAttendeeVibe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vibe', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destiny_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.destinyteam')),
            ],
        ),
        migrations.AddField(
            model_name='destinyteam',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='destiny_team_attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destinyteam',
            name='table',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.table'),
        ),
        migrations.CreateModel(
            name='AttendeePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference', models.CharField(choices=[('Y', 'Yay'), ('N', 'Nay')], max_length=1)),
                ('preferee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_preference_preferee', to=settings.AUTH_USER_MODEL)),
                ('preferer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_preference_preferer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
