# Generated by Django 4.2.2 on 2024-01-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_destinyteam_remove_attendee_hardware_hack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinyteamattendeevibe',
            old_name='attende',
            new_name='attendee',
        ),
    ]
