# Generated by Django 4.2.2 on 2024-01-23 22:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0018_rename_attende_destinyteamattendeevibe_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('H', 'Hardware Hack'), ('M', 'Meta'), ('Q', 'Snapdragon Spaces'), ('X', 'XREAL'), ('S', 'Snap Spectacles')], max_length=30),
        ),
    ]
