# Generated by Django 4.2.2 on 2024-01-24 04:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0019_team_destiny_hardware'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinyteam',
            name='destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('H', 'Hardware Hack'), ('M', 'Meta'), ('Q', 'Snapdragon Spaces'), ('X', 'XREAL'), ('S', 'Snap Spectacles')], max_length=30),
        ),
        migrations.AddField(
            model_name='destinyteam',
            name='hardware_hack',
            field=models.BooleanField(default=False),
        ),
    ]
