# Generated by Django 4.2.2 on 2024-01-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_alter_workshop_name'),
        ('infrastructure', '0020_destinyteam_destiny_hardware_and_more'),
    ]

    operations = [
    ]
