# Generated by Django 4.2.2 on 2024-01-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0021_merge_20240125_1613'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendee',
            index=models.Index(fields=['authentication_id'], name='infrastruct_authent_8241f7_idx'),
        ),
    ]
