# Generated by Django 4.2.2 on 2024-01-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0022_alter_destinyteam_table'),
        ('infrastructure', '0022_attendee_infrastruct_authent_8241f7_idx'),
    ]

    operations = [
    ]
