# Generated by Django 4.2.2 on 2024-10-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_remove_application_disabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='theme_detail_one',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='theme_detail_three',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='theme_detail_two',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='theme_interest_track_one',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='theme_interest_track_two',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, null=True),
        ),
    ]
