# Generated by Django 4.2.2 on 2024-10-17 17:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0027_application_theme_detail_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hardware_hack_detail',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', '3D Printing'), ('B', 'Soldering'), ('C', 'Circuits'), ('D', 'Arduino'), ('E', 'ESP32'), ('F', 'Unity'), ('G', 'Physical Prototyping'), ('H', 'I have no prior experience'), ('O', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='under_18_by_date',
            field=models.BooleanField(help_text='Will you be under 18 on January 23, 2025', null=True),
        ),
    ]
