# Generated by Django 4.2.2 on 2024-10-24 00:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0028_application_hardware_hack_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='race_ethnic_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('B', 'Black, African American, or of African descent'), ('C', 'Hispanic, Latino, Latina, Latinx, or of Latinx or Spanish-speaking descent'), ('D', 'Middle Eastern, North African, or of North African descent'), ('E', 'Native American, American Indian, Alaska Native, or Indigenous'), ('F', 'Pacific Islander or Native Hawaiian'), ('G', 'White or of European descent'), ('H', 'Multi-racial or multi-ethnic'), ('I', 'I prefer not to say'), ('J', 'East Asian'), ('K', 'South Asian'), ('L', 'Southeast Asian'), ('M', 'Central Asian'), ('O', 'Other')], max_length=26),
        ),
    ]
