# Generated by Django 4.2.2 on 2024-11-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0030_alter_application_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='reporter_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorhelprequest',
            name='reporter_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
