# Generated by Django 4.2.2 on 2024-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0032_team_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='special_track_snapdragon_spaces_interest',
            new_name='special_interest_track_one',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='special_track_future_constructors_interest',
            new_name='special_interest_track_two',
        ),
        migrations.AddField(
            model_name='attendee',
            name='visa_support_form_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendeepreference',
            name='preference',
            field=models.CharField(choices=[('Y', 'Yay'), ('N', 'Nay'), ('T', 'Tbd')], max_length=1),
        ),
    ]
