# Generated by Django 4.2.2 on 2024-12-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0033_rename_special_track_snapdragon_spaces_interest_attendee_special_interest_track_one_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="breakthrough_hacks_interest",
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="attendee",
            name="loaner_headset_preference",
            field=models.CharField(
                choices=[
                    ("META", "Meta Quest 3"),
                    ("SNAP", "Snap Spectacles"),
                    ("BYOD", "I am bringing my own XR device to work with."),
                    (
                        "HWHACK",
                        "I’ve chosen the Hardware Hack, so I will probably not need a headset.",
                    ),
                    ("TBD", "I’m not sure yet"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
