# Generated by Django 4.2.2 on 2025-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0036_remove_team_track_team_tracks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="track",
            field=models.CharField(
                choices=[
                    ("F", "Founders Lab"),
                    ("C", "Open Lab (AKA Community Hack)"),
                    ("S", "Connecting for Change with Social XR"),
                    ("E", "Augmented Engineering"),
                    ("D", "Digitizing Sustainability"),
                    ("A", "AeroSpatial Exploration"),
                    ("L", "Augmented Intelligence"),
                    ("W", "Hardware hack"),
                    ("H", "Healthcare"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
