# Generated by Django 4.2.2 on 2025-01-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0037_team_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='track',
        ),
    ]
