# Generated by Django 4.2.2 on 2025-01-22 22:29

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0039_alter_attendee_prefers_destiny_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='startup_hack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='intended_tracks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Open Lab (AKA Community Hack)'), ('S', 'Connecting for Change with Social XR'), ('E', 'Augmented Engineering'), ('D', 'Digitizing Sustainability'), ('A', 'AeroSpatial Exploration'), ('L', 'Augmented Intelligence'), ('H', 'Healthcare')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='destinyteam',
            name='track',
            field=models.CharField(choices=[('C', 'Open Lab (AKA Community Hack)'), ('S', 'Connecting for Change with Social XR'), ('E', 'Augmented Engineering'), ('D', 'Digitizing Sustainability'), ('A', 'AeroSpatial Exploration'), ('L', 'Augmented Intelligence'), ('H', 'Healthcare')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmentorhelprequest',
            name='reporter_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentorhelprequest',
            name='reporter_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tracks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Open Lab (AKA Community Hack)'), ('S', 'Connecting for Change with Social XR'), ('E', 'Augmented Engineering'), ('D', 'Digitizing Sustainability'), ('A', 'AeroSpatial Exploration'), ('L', 'Augmented Intelligence'), ('H', 'Healthcare')], max_length=15),
        ),
    ]
