# Generated by Django 4.2.2 on 2025-01-26 08:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0040_team_startup_hack_alter_attendee_intended_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='census_location_override',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='census_taker_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_primary_contact',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='prefers_destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Best Lifestyle Experience with Meta Quest'), ('Q', 'Best in World Building with Horizon Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Best use of Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name='destinyteam',
            name='destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Best Lifestyle Experience with Meta Quest'), ('Q', 'Best in World Building with Horizon Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Best use of Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='relates_to_destiny_hardware',
            field=models.CharField(choices=[('M', 'Best Lifestyle Experience with Meta Quest'), ('Q', 'Best in World Building with Horizon Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Best use of Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(choices=[('MH', 'Morss Hall'), ('AT', 'Atlantis'), ('NE', 'Neptune'), ('24', '32-124'), ('44', '32-144'), ('41', '32-141')], default='MH', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Best Lifestyle Experience with Meta Quest'), ('Q', 'Best in World Building with Horizon Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Best use of Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.table'),
        ),
    ]
