# Generated by Django 4.2.2 on 2025-10-17 23:00

from django.db import migrations, models
from django.utils import timezone
import datetime
import uuid


def create_first_event(apps, schema_editor):
    """Create the first event for MIT Reality Hack 2025."""
    Event = apps.get_model('infrastructure', 'Event')
    
    # Use a fixed UUID so it can be referenced in subsequent migrations
    FIRST_EVENT_UUID = uuid.UUID('888a5508-ea40-4453-84bc-a0e4a03e491b')
    
    default_event = Event.objects.create(
        id=FIRST_EVENT_UUID,
        name="Reality Hack at MIT 2025",
        start_date=datetime.datetime(2025, 1, 23, 0, 0, 0, tzinfo=timezone.utc),
        end_date=datetime.datetime(2025, 1, 26, 23, 59, 59, tzinfo=timezone.utc),
        is_active=True,
    )
    
    print(f"✓ Created first event: {default_event.name} (ID: {default_event.id})")


def reverse_first_event(apps, schema_editor):
    """Remove the first event if migration is reversed."""
    Event = apps.get_model('infrastructure', 'Event')
    Event.objects.filter(name="MIT Reality Hack 2025").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0042_alter_attendee_intended_tracks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False, help_text='Only one event should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendee',
            name='loaner_headset_preference',
            field=models.CharField(choices=[('META', 'Meta Quest 3'), ('SNAP', 'Snap Spectacles'), ('BYOD', 'I am bringing my own XR device to work with.'), ('HWHACK', "I've chosen the Hardware Hack, so I will probably not need a headset."), ('TBD', "I'm not sure yet")], max_length=6, null=True),
        ),
        # Create the first event
        migrations.RunPython(create_first_event, reverse_first_event),
    ]
