# Generated by Django 4.2.2 on 2025-10-17 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0043_event_alter_attendee_loaner_headset_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='event_year',
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendeepreference',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinyteam',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinyteamattendeevibe',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardware',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaredevice',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwarerequest',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhardwaredevice',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.event'),
        ),
        migrations.AddField(
            model_name='historicalmentorhelprequest',
            name='event',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='infrastructure.event'),
        ),
        migrations.AddField(
            model_name='lighthouse',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorhelprequest',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshopattendee',
            name='event',
            field=models.ForeignKey(default='888a5508-EA40-4453-84bc-a0e4a03e491b', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['event', 'email'], name='infrastruct_event_i_8bcba7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['event', 'status'], name='infrastruct_event_i_868210_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwaredevice',
            index=models.Index(fields=['event', 'hardware'], name='infrastruct_event_i_93234e_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwarerequest',
            index=models.Index(fields=['event', 'hardware', 'status'], name='infrastruct_event_i_f61d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorhelprequest',
            index=models.Index(fields=['event', 'status', 'created_at'], name='infrastruct_event_i_3ba456_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['event', 'name'], name='infrastruct_event_i_cacf7a_idx'),
        ),
    ]
