# Generated by Django 4.2.2 on 2025-10-23 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid
import logging
from django.core.management import call_command


def migrate_to_dynamic_questions(apps, schema_editor):
    """Run the data migration to populate dynamic questions"""
    logger = logging.getLogger(__name__)
    try:
        call_command('migrate_to_dynamic_questions')
    except Exception as e:
        logger.error(f"Failed to migrate to dynamic questions: {e}")
        raise


def reverse_migrate(apps, schema_editor):
    """Reverse operation - remove all dynamic questions and responses"""
    ApplicationQuestion = apps.get_model('infrastructure', 'ApplicationQuestion')
    ApplicationQuestionChoice = apps.get_model('infrastructure', 'ApplicationQuestionChoice')
    ApplicationResponse = apps.get_model('infrastructure', 'ApplicationResponse')

    ApplicationResponse.objects.all().delete()
    ApplicationQuestionChoice.objects.all().delete()
    ApplicationQuestion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0045_application_other_skills_experiences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_key', models.CharField(help_text="Internal identifier like 'hardware_hack_interest'", max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('S', 'Single Choice'), ('M', 'Multiple Choice'), ('T', 'Text Response'), ('L', 'Long Text/Essay')], max_length=1)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('trigger_choices', models.JSONField(blank=True, default=list, help_text='List of choice_keys from parent that trigger this question. Empty = always show')),
                ('max_length', models.IntegerField(blank=True, default=2000, help_text='Maximum character length for text responses', null=True)),
                ('min_length', models.IntegerField(blank=True, help_text='Minimum character length for text responses', null=True)),
                ('placeholder_text', models.CharField(blank=True, help_text='Placeholder text for text inputs', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event')),
                ('parent_question', models.ForeignKey(blank=True, help_text='If set, this question only appears based on parent response', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='infrastructure.applicationquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationQuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice_key', models.CharField(help_text="Short code like 'A', 'B', 'Y', 'N'", max_length=10)),
                ('choice_text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='infrastructure.applicationquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text_snapshot', models.TextField(help_text='Question text at time of response')),
                ('choices_snapshot', models.JSONField(default=dict, help_text="{'choice_key': 'choice_text'} at time of response")),
                ('selected_keys_snapshot', models.JSONField(default=list, help_text='List of choice_keys selected, preserved snapshot')),
                ('text_response', models.TextField(blank=True, help_text='Free-form text response for TEXT question types')),
                ('text_response_snapshot', models.TextField(blank=True, help_text='Snapshot of text response at time of submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='infrastructure.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='infrastructure.applicationquestion')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='responses', to='infrastructure.applicationquestionchoice')),
            ],
            options={
                'indexes': [models.Index(fields=['application'], name='infrastruct_applica_1b37ad_idx'), models.Index(fields=['question'], name='infrastruct_questio_9e769a_idx')],
                'unique_together': {('application', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='applicationquestionchoice',
            index=models.Index(fields=['question', 'order'], name='infrastruct_questio_108652_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationquestionchoice',
            unique_together={('question', 'choice_key')},
        ),
        migrations.AddIndex(
            model_name='applicationquestion',
            index=models.Index(fields=['event', 'question_key'], name='infrastruct_event_i_b6d625_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationquestion',
            index=models.Index(fields=['event', 'order'], name='infrastruct_event_i_68451a_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationquestion',
            index=models.Index(fields=['parent_question'], name='infrastruct_parent__7222ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationquestion',
            unique_together={('event', 'question_key')},
        ),
        migrations.RunPython(
            migrate_to_dynamic_questions,
            reverse_code=reverse_migrate
        ),
    ]
