# Generated by Django 4.2.2 on 2025-11-06 21:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0045_applicationquestion_applicationquestionchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='other_skills_experiences',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hardware_hack_interest',
            field=models.CharField(choices=[('A', "Not at all interested; I'll pass"), ('B', 'Some mild interest'), ('C', 'Most likely'), ('D', '100%; I want to join')], default='B', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='previous_participation',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', '2016'), ('B', '2017'), ('C', '2018'), ('D', '2019'), ('E', '2020'), ('F', '2022'), ('G', '2023'), ('H', '2024'), ('I', '2025')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='under_18_by_date',
            field=models.BooleanField(help_text='Will you be under 18 on January 22, 2026', null=True),
        ),
    ]
