# Generated by Django 4.2.2 on 2025-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0046_applicationquestion_applicationquestionchoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('email', 'event')},
        ),
    ]
