# Generated by Django 4.2.2 on 2025-11-15 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command
import multiselectfield.db.fields
import phonenumber_field.modelfields
import uuid
import logging


def migrate_attendee_event_rsvp(apps, schema_editor):
    """Migrate attendee event rsvp data to EventRsvp model"""
    logger = logging.getLogger(__name__)
    try:
        call_command('migrate_attendee_event_rsvp')
    except Exception as e:
        logger.error(f"Failed to migrate attendee event rsvp data: {e}")
        raise
    
def reverse_migrate_attendee_event_rsvp(apps, schema_editor):
    """Reverse the migration of attendee event rsvp data to EventRsvp model"""
    logger = logging.getLogger(__name__)
    try:
        EventRsvp = apps.get_model('infrastructure', 'EventRsvp')
        EventRsvp.objects.all().delete()
    except Exception as e:
        logger.error(f"Failed to reverse migrate attendee event rsvp data: {e}")
        raise

class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0047_alter_application_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communications_platform_username', models.CharField(help_text='I.e., a Discord username', max_length=40, null=True)),
                ('participation_role', models.CharField(choices=[('A', 'Digital/Creative Designer'), ('D', 'Developer'), ('S', 'Domain or other Specialized Skill Expert'), ('P', 'Project Manager')], default='S', max_length=1, null=True)),
                ('shirt_size', models.CharField(choices=[('1', 'XS'), ('2', 'S'), ('3', 'M'), ('4', 'L'), ('5', 'XL'), ('6', 'XXL')], default='3', max_length=1, null=True)),
                ('intended_tracks', multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Open Lab (AKA Community Hack)'), ('S', 'Connecting for Change with Social XR'), ('E', 'Augmented Design & Engineering'), ('D', 'Standing on the Shoulders of Sustainability'), ('A', 'AeroSpatial Exploration'), ('L', 'Augmented Intelligence'), ('H', 'Healthcare')], max_length=7, null=True)),
                ('intended_hardware_hack', models.BooleanField(default=False)),
                ('prefers_destiny_hardware', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Best MR Lifestyle App for Meta Quest'), ('Q', 'Best Lifestyle World with Meta Horizons Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=21, null=True)),
                ('dietary_restrictions', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Vegetarian'), ('2', 'Vegan'), ('3', 'Gluten free'), ('4', 'Halal'), ('5', 'Lactose Intolerant'), ('6', 'Kosher'), ('7', 'Other')], max_length=15, null=True)),
                ('dietary_restrictions_other', models.CharField(max_length=40, null=True)),
                ('dietary_allergies', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Nut allergy'), ('2', 'Shellfish allergy'), ('3', 'Dairy allergy'), ('4', 'Soy allergy'), ('5', 'Other')], max_length=10, null=True)),
                ('dietary_allergies_other', models.CharField(max_length=40, null=True)),
                ('additional_accommodations', models.TextField(max_length=200, null=True)),
                ('us_visa_support_is_required', models.BooleanField()),
                ('visa_support_form_confirmation', models.BooleanField(default=False)),
                ('us_visa_letter_of_invitation_required', models.BooleanField(default=False, null=True)),
                ('us_visa_support_full_name', models.CharField(max_length=200, null=True)),
                ('us_visa_support_document_number', models.CharField(max_length=50, null=True)),
                ('us_visa_support_national_identification_document_type', models.CharField(choices=[('P', 'Passport'), ('N', 'National/State/Municipal ID')], max_length=1, null=True)),
                ('us_visa_support_citizenship', models.CharField(choices=[('AW', 'Aruba'), ('AF', 'Afghanistan'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AS', 'American Samoa'), ('AQ', 'Antarctica'), ('TF', 'French Southern Territories'), ('AG', 'Antigua and Barbuda'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BI', 'Burundi'), ('BE', 'Belgium'), ('BJ', 'Benin'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BF', 'Burkina Faso'), ('BD', 'Bangladesh'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BS', 'Bahamas'), ('BA', 'Bosnia and Herzegovina'), ('BL', 'Saint Barthélemy'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('BM', 'Bermuda'), ('BO', 'Bolivia, Plurinational State of'), ('BR', 'Brazil'), ('BB', 'Barbados'), ('BN', 'Brunei Darussalam'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('CF', 'Central African Republic'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CH', 'Switzerland'), ('CL', 'Chile'), ('CN', 'China'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CD', 'Congo, The Democratic Republic of the'), ('CG', 'Congo'), ('CK', 'Cook Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CV', 'Cabo Verde'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CX', 'Christmas Island'), ('KY', 'Cayman Islands'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('EH', 'Western Sahara'), ('ES', 'Spain'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FR', 'France'), ('FO', 'Faroe Islands'), ('FM', 'Micronesia, Federated States of'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GE', 'Georgia'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GM', 'Gambia'), ('GW', 'Guinea-Bissau'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GD', 'Grenada'), ('GL', 'Greenland'), ('GT', 'Guatemala'), ('GF', 'French Guiana'), ('GU', 'Guam'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IE', 'Ireland'), ('IR', 'Iran, Islamic Republic of'), ('IQ', 'Iraq'), ('IS', 'Iceland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KN', 'Saint Kitts and Nevis'), ('KR', 'Korea, Republic of'), ('KW', 'Kuwait'), ('LA', "Lao People's Democratic Republic"), ('LB', 'Lebanon'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('MO', 'Macao'), ('MF', 'Saint Martin (French part)'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Moldova, Republic of'), ('MG', 'Madagascar'), ('MV', 'Maldives'), ('MX', 'Mexico'), ('MH', 'Marshall Islands'), ('MK', 'North Macedonia'), ('ML', 'Mali'), ('MT', 'Malta'), ('MM', 'Myanmar'), ('ME', 'Montenegro'), ('MN', 'Mongolia'), ('MP', 'Northern Mariana Islands'), ('MZ', 'Mozambique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MQ', 'Martinique'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('YT', 'Mayotte'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NU', 'Niue'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PA', 'Panama'), ('PN', 'Pitcairn'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PW', 'Palau'), ('PG', 'Papua New Guinea'), ('PL', 'Poland'), ('PR', 'Puerto Rico'), ('KP', "Korea, Democratic People's Republic of"), ('PT', 'Portugal'), ('PY', 'Paraguay'), ('PS', 'Palestine, State of'), ('PF', 'French Polynesia'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SD', 'Sudan'), ('SN', 'Senegal'), ('SG', 'Singapore'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('SJ', 'Svalbard and Jan Mayen'), ('SB', 'Solomon Islands'), ('SL', 'Sierra Leone'), ('SV', 'El Salvador'), ('SM', 'San Marino'), ('SO', 'Somalia'), ('PM', 'Saint Pierre and Miquelon'), ('RS', 'Serbia'), ('SS', 'South Sudan'), ('ST', 'Sao Tome and Principe'), ('SR', 'Suriname'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SE', 'Sweden'), ('SZ', 'Eswatini'), ('SX', 'Sint Maarten (Dutch part)'), ('SC', 'Seychelles'), ('SY', 'Syrian Arab Republic'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TM', 'Turkmenistan'), ('TL', 'Timor-Leste'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TV', 'Tuvalu'), ('TW', 'Taiwan, Province of China'), ('TZ', 'Tanzania, United Republic of'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('US', 'United States'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City State)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela, Bolivarian Republic of'), ('VG', 'Virgin Islands, British'), ('VI', 'Virgin Islands, U.S.'), ('VN', 'Viet Nam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, null=True)),
                ('us_visa_support_address', models.TextField(max_length=500, null=True)),
                ('under_18_by_date', models.BooleanField(help_text='Will you be under 18 on January 22, 2026', null=True)),
                ('parental_consent_form_signed', models.BooleanField(default=None, null=True)),
                ('agree_to_media_release', models.BooleanField(default=False)),
                ('agree_to_liability_release', models.BooleanField(default=False)),
                ('agree_to_rules_code_of_conduct', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('personal_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emergency_contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('special_interest_track_one', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('special_interest_track_two', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('breakthrough_hacks_interest', models.TextField(max_length=2000, null=True)),
                ('loaner_headset_preference', models.CharField(choices=[('META', 'Meta Quest 3'), ('SNAP', 'Snap Spectacles'), ('BYOD', 'I am bringing my own XR device to work with.'), ('HWHACK', "I've chosen the Hardware Hack, so I will probably not need a headset."), ('TBD', "I'm not sure yet")], max_length=6, null=True)),
                ('app_in_store', models.CharField(help_text='AR or VR apps in any store? And if so, which ones?', max_length=250, null=True)),
                ('currently_build_for_xr', models.CharField(max_length=250, null=True)),
                ('currently_use_xr', models.CharField(max_length=250, null=True)),
                ('non_xr_talents', models.CharField(max_length=250, null=True)),
                ('ar_vr_ap_in_store', models.CharField(max_length=250, null=True)),
                ('reality_hack_project_to_product', models.BooleanField(default=False)),
                ('participation_class', models.CharField(choices=[('P', 'Participant'), ('M', 'Mentor'), ('J', 'Judge'), ('S', 'Sponsor'), ('V', 'Volunteer'), ('O', 'Organizer'), ('G', 'Guardian'), ('E', 'Media')], default='P', max_length=1)),
                ('status', models.CharField(choices=[('R', "RSVP'd"), ('A', 'Arrived'), ('C', 'Canceled')], default='R', max_length=1)),
                ('checked_in_at', models.DateTimeField(null=True)),
                ('sponsor_company', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.application')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='infrastructure.event')),
                ('guardian_of', models.ManyToManyField(blank=True, related_name='rsvp_attendee_guardian_of', to=settings.AUTH_USER_MODEL)),
                ('sponsor_handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp_attendee_sponsor_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'attendee'], name='infrastruct_event_i_6ab6c6_idx'), models.Index(fields=['event', 'participation_role'], name='infrastruct_event_i_ce6d17_idx')],
                'unique_together': {('attendee', 'event')},
            },
        ),
        migrations.RunPython(
            migrate_attendee_event_rsvp,
            reverse_code=reverse_migrate_attendee_event_rsvp
        ),
    ]
