# Generated by Django 4.2.2 on 2025-12-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0048_eventrsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrsvp',
            old_name='communications_platform_username',
            new_name='communication_platform_username',
        ),
        migrations.AddField(
            model_name='application',
            name='mentor_own_troubleshooting_devices',
            field=models.TextField(blank=True, help_text='List devices you are willing to bring to assist with troubleshooting', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='participation_class',
            field=models.CharField(choices=[('P', 'Participant'), ('M', 'Mentor'), ('J', 'Judge'), ('S', 'Sponsor'), ('V', 'Volunteer'), ('O', 'Organizer'), ('G', 'Guardian'), ('E', 'Media')], default='P', max_length=1),
        ),
    ]
