# Generated by Django 4.2.2 on 2025-12-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0049_rename_communications_platform_username_eventrsvp_communication_platform_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='device_preference_ranked',
            field=models.CharField(blank=True, help_text='List other devices you are interested in ranked by preference.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='loaner_headset_preference',
            field=models.CharField(choices=[('META', 'Meta Quest 3'), ('RB_META_AI', 'Ray-Ban Meta AI lasses'), ('ARDUINO_UNO', 'Arduino Uno Kits'), ('SAMSUNG_GALAXY_XR', 'Samsung Galaxy XR'), ('RAYNEO', 'RayNeo'), ('RAVEN_AR', 'Raven AR'), ('SNAP', 'Snap Spectacles'), ('APPLE_VISION_PRO', 'Apple Vision Pro'), ('BLACKMAGIC', 'Blackmagic URSA Cine Immersive Camera'), ('XREAL', 'XREAL'), ('PICO', 'Pico'), ('OPENBCI', 'OpenBCI Sensors'), ('BYOD', 'I am bringing my own XR device to work with.'), ('HWHACK', "I've chosen the Hardware Hack, so I will probably not need a headset."), ('TBD', "I'm not sure yet")], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='loaner_headset_preference',
            field=models.CharField(choices=[('META', 'Meta Quest 3'), ('RB_META_AI', 'Ray-Ban Meta AI lasses'), ('ARDUINO_UNO', 'Arduino Uno Kits'), ('SAMSUNG_GALAXY_XR', 'Samsung Galaxy XR'), ('RAYNEO', 'RayNeo'), ('RAVEN_AR', 'Raven AR'), ('SNAP', 'Snap Spectacles'), ('APPLE_VISION_PRO', 'Apple Vision Pro'), ('BLACKMAGIC', 'Blackmagic URSA Cine Immersive Camera'), ('XREAL', 'XREAL'), ('PICO', 'Pico'), ('OPENBCI', 'OpenBCI Sensors'), ('BYOD', 'I am bringing my own XR device to work with.'), ('HWHACK', "I've chosen the Hardware Hack, so I will probably not need a headset."), ('TBD', "I'm not sure yet")], max_length=24, null=True),
        ),
    ]
