# Generated by Django 4.2.2 on 2025-12-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0050_attendee_device_preference_ranked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='device_preference_ranked',
            field=models.CharField(blank=True, help_text='List other devices you are interested in ranked by preference.', max_length=1000, null=True),
        ),
    ]
