# Generated by Django 4.2.2 on 2026-01-22 20:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0051_eventrsvp_device_preference_ranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='floor',
            field=models.CharField(blank=True, help_text='Optional free-form floor descriptor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about the table', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(choices=[('ST', 'Stata'), ('WK', 'Walker'), ('SC', 'Student Center (Straton)'), ('BC', 'Barcelona')], default='WK', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.CharField(choices=[('MH', 'Morss Hall'), ('AT', 'Atlantis'), ('NE', 'Neptune'), ('24', '32-124'), ('44', '32-144'), ('41', '32-141'), ('MZ', 'Mezzanine'), ('TC', 'Twenty Chimneys'), ('301', 'W20-301+302'), ('SP', 'Sala de Puerto Rico'), ('401', 'W20-401'), ('RM', 'Remote')], default='MH', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='destiny_hardware',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Best MR Lifestyle App for Meta Quest'), ('Q', 'Best Lifestyle World with Meta Horizons Worlds'), ('T', 'Best use of Haptics'), ('S', 'Snap Spectacles Challenge'), ('N', 'Pioneering a Neuroadaptive Future'), ('X', 'Best Use of ShapesXR'), ('Y', 'Best use of STYLY'), ('L', 'Best use of Lambda AI Cloud Services'), ('U', 'Qualcomm IoT'), ('V', 'Best use of Apple Vision Pro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='devpost_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tracks',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('C', 'Open Lab (AKA Community Hack)'), ('S', 'Connecting for Change with Social XR'), ('E', 'Augmented Design & Engineering'), ('D', 'Standing on the Shoulders of Sustainability'), ('A', 'AeroSpatial Exploration'), ('L', 'Augmented Intelligence'), ('H', 'Healthcare')], max_length=15, null=True),
        ),
    ]
