# Generated by Django 4.2.2 on 2026-01-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0054_add_event_scoped_track_hardware_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='community_hack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventdestinyhardware',
            name='code',
            field=models.CharField(help_text='Six char code', max_length=6),
        ),
        migrations.AlterField(
            model_name='eventtrack',
            name='code',
            field=models.CharField(help_text='Six char code', max_length=6),
        ),
    ]
