# Generated by Django 4.2.20 on 2026-03-29 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0055_team_community_hack_alter_eventdestinyhardware_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorEventEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('EC', 'Ecosystem'), ('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3'), ('T4', 'Tier 4'), ('T5', 'Tier 5')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='sponsor_company',
        ),
        migrations.AddIndex(
            model_name='eventrsvp',
            index=models.Index(fields=['event', 'sponsor_company'], name='infrastruct_event_i_855b42_idx'),
        ),
        migrations.AddField(
            model_name='sponsoreventengagement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_event_engagements', to='infrastructure.event'),
        ),
        migrations.AddField(
            model_name='sponsoreventengagement',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_event_engagements', to='infrastructure.sponsor'),
        ),
        migrations.AddField(
            model_name='eventdestinyhardware',
            name='sponsor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_destiny_hardware', to='infrastructure.sponsor'),
        ),
        migrations.AddField(
            model_name='eventtrack',
            name='sponsor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_tracks', to='infrastructure.sponsor'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='sponsor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hardware_items', to='infrastructure.sponsor'),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='sponsor_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_company', to='infrastructure.sponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsoreventengagement',
            unique_together={('sponsor', 'event')},
        ),
    ]
