# Generated by Django 4.2.2 on 2026-04-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0056_sponsor_sponsoreventengagement_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdestinyhardware",
            name="sponsor_company",
        ),
        migrations.RemoveField(
            model_name="eventtrack",
            name="sponsor_company",
        ),
        migrations.AddField(
            model_name="eventdestinyhardware",
            name="sponsor_companies",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_destiny_hardware",
                to="infrastructure.sponsor",
            ),
        ),
        migrations.AddField(
            model_name="eventtrack",
            name="sponsor_companies",
            field=models.ManyToManyField(
                blank=True, related_name="event_tracks", to="infrastructure.sponsor"
            ),
        ),
        migrations.RemoveField(
            model_name="hardware",
            name="relates_to_event_destiny_hardware",
        ),
        migrations.AddField(
            model_name="hardware",
            name="relates_to_event_destiny_hardware",
            field=models.ManyToManyField(
                blank=True,
                help_text="Event-scoped destiny hardware association",
                related_name="hardware_items",
                to="infrastructure.eventdestinyhardware",
            ),
        ),
    ]
