# Generated by Django 4.2.20 on 2026-04-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0057_sponsor_companies_m2m_hardware_destiny_m2m'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationResponse',
            new_name='ApplicationQuestionResponse',
        ),
        migrations.RenameModel(
            old_name='ApplicationQuestion',
            new_name='ConfigurableQuestion',
        ),
        migrations.RenameModel(
            old_name='ApplicationQuestionChoice',
            new_name='ConfigurableQuestionChoice',
        ),
        migrations.RenameIndex(
            model_name='applicationquestionresponse',
            new_name='infrastruct_applica_652d7e_idx',
            old_name='infrastruct_applica_1b37ad_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationquestionresponse',
            new_name='infrastruct_questio_da4736_idx',
            old_name='infrastruct_questio_9e769a_idx',
        ),
        migrations.RenameIndex(
            model_name='configurablequestion',
            new_name='infrastruct_event_i_f75dba_idx',
            old_name='infrastruct_event_i_b6d625_idx',
        ),
        migrations.RenameIndex(
            model_name='configurablequestion',
            new_name='infrastruct_event_i_ac3fde_idx',
            old_name='infrastruct_event_i_68451a_idx',
        ),
        migrations.RenameIndex(
            model_name='configurablequestion',
            new_name='infrastruct_parent__30d7a2_idx',
            old_name='infrastruct_parent__7222ea_idx',
        ),
        migrations.RenameIndex(
            model_name='configurablequestionchoice',
            new_name='infrastruct_questio_e9d16a_idx',
            old_name='infrastruct_questio_108652_idx',
        ),
    ]
