# Generated by Django 4.2.20 on 2026-04-12 16:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0058_rename_application_question_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurablequestion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='configurablequestion',
            name='form_type',
            field=models.CharField(choices=[('A', 'Application'), ('R', 'RSVP')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='configurablequestion',
            unique_together={('event', 'form_type', 'question_key')},
        ),
        migrations.CreateModel(
            name='RsvpQuestionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text_snapshot', models.TextField()),
                ('choices_snapshot', models.JSONField(default=dict)),
                ('selected_keys_snapshot', models.JSONField(default=list)),
                ('text_response', models.TextField(blank=True)),
                ('text_response_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rsvp_responses', to='infrastructure.configurablequestion')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='infrastructure.eventrsvp')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='rsvp_responses', to='infrastructure.configurablequestionchoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
