# Generated by Django 4.2.20 on 2026-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0059_add_rsvp_question_responses_and_conf_question_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestionresponse',
            name='choices_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='applicationquestionresponse',
            name='question_text_snapshot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='applicationquestionresponse',
            name='selected_keys_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='applicationquestionresponse',
            name='text_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicationquestionresponse',
            name='text_response_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='rsvpquestionresponse',
            unique_together={('rsvp', 'question')},
        ),
        migrations.AddIndex(
            model_name='rsvpquestionresponse',
            index=models.Index(fields=['rsvp'], name='infrastruct_rsvp_id_83da17_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvpquestionresponse',
            index=models.Index(fields=['question'], name='infrastruct_questio_47a739_idx'),
        ),
    ]
