# Generated by Django 4.2.20 on 2026-06-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0060_migrate_application_question_to_abstract_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurablequestionchoice',
            name='choice_key',
            field=models.CharField(
                help_text=(
                    "Short code like 'A', 'B', 'Y', 'N', "
                    "or device keys like 'APPLE_VISION_PRO'"
                ),
                max_length=24,
            ),
        ),
    ]
