# Generated by Django 4.2.20 on 2026-06-09 00:00

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def seed_and_migrate_rsvp_questions(apps, schema_editor):
    from infrastructure.rsvp_question_migration import run_rsvp_question_migration

    run_rsvp_question_migration()


def reverse_seed_and_migrate_rsvp_questions(apps, schema_editor):
    Event = apps.get_model('infrastructure', 'Event')
    ConfigurableQuestion = apps.get_model('infrastructure', 'ConfigurableQuestion')
    EventRsvp = apps.get_model('infrastructure', 'EventRsvp')
    RsvpQuestionResponse = apps.get_model('infrastructure', 'RsvpQuestionResponse')

    event_names = ('Reality Hack at MIT 2025', 'Reality Hack at MIT 2026')
    events = Event.objects.filter(name__in=event_names)

    for event in events:
        rsvp_ids = EventRsvp.objects.filter(event=event).values_list('id', flat=True)
        RsvpQuestionResponse.objects.filter(rsvp_id__in=rsvp_ids).delete()
        ConfigurableQuestion.objects.filter(
            event=event,
            form_type='R',
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0061_alter_configurablequestionchoice_choice_key'),
    ]

    operations = [
        migrations.RunPython(
            seed_and_migrate_rsvp_questions,
            reverse_code=reverse_seed_and_migrate_rsvp_questions,
        ),
    ]
