# Generated by Django 4.2.20 on 2026-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0062_seed_rsvp_questions_and_migrate_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AI', 'Accepted, In-Person'), ('AO', 'Accepted, Online'), ('WI', 'Wait-list, In-Person'), ('WO', 'Wait-list, Online'), ('A', 'Accepted'), ('W', 'Waitlist'), ('D', 'Declined')], default=None, max_length=2, null=True),
        ),
    ]
