# Generated by Django 4.2.20 on 2026-09-02 03:14

from django.db import migrations


legacy_status_map = {
    'AI': 'A',
    'AO': 'A',
    'WI': 'W',
    'WO': 'W',
    'D': 'D',
    'A': 'A',
    'W': 'W',
}


def migrate_application_status(apps, schema_editor):
    Application = apps.get_model('infrastructure', 'Application')

    for old_status, new_status in legacy_status_map.items():
        Application.objects.filter(status=old_status).update(status=new_status)


def reverse_migration(apps, schema_editor):
    raise RuntimeError(
        'Cannot reverse this migration: application status mapping is lossy.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0063_alter_application_status'),
    ]

    operations = [
        migrations.RunPython(migrate_application_status, reverse_migration),
    ]
