# Generated by Django 4.2.20 on 2026-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0064_migrate_application_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('email', 'event', 'participation_class')},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('W', 'Waitlist'), ('D', 'Declined')], default=None, max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'A')), fields=('email', 'event'), name='unique_accepted_in_person_per_email_event'),
        ),
    ]
