# Generated by Django 4.2.30 on 2026-09-20 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0065_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('application_confirmation', 'Application Confirmation'), ('rsvp_request', 'RSVP Request'), ('rsvp_confirmation', 'RSVP Confirmation'), ('multiple_users_found', 'Multiple Users Found'), ('keycloak_account_error', 'Keycloak Account Error')], max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='infrastructure.application')),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to=settings.AUTH_USER_MODEL)),
                ('event_rsvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_records', to='infrastructure.eventrsvp')),
            ],
            options={
                'indexes': [models.Index(fields=['application', 'email_type'], name='infrastruct_applica_f5560d_idx'), models.Index(fields=['event_rsvp', 'email_type'], name='infrastruct_event_r_2950db_idx'), models.Index(fields=['attendee', 'email_type'], name='infrastruct_attende_dfb01b_idx'), models.Index(fields=['recipient_email'], name='infrastruct_recipie_956fa3_idx')],
            },
        ),
    ]
