MENTOR_HELP_REQUEST_TOPICS = [
    ('AI_CHAT', 'AI - Chat'),
    ('AI_GENAI', 'AI - GenAI'),
    ('AI_OTHER', 'AI - Other'),
    ('AI_VISION_SENSING', 'AI - Vision and Sensing'),
    ('AUDIO_MUSIC', 'Audio - Music'),
    ('AUDIO_OTHER', 'Audio - Other'),
    ('AUDIO_SPATIAL', 'Audio - Spatial Audio'),
    ('AVP_ARKIT', 'AVP - ARKit'),
    ('AVP_OTHER', 'AVP - Other'),
    ('AVP_REALITY_COMPOSER', 'AVP - Reality Composer'),
    ('AVP_SHAREPLAY', 'AVP - SharePlay'),
    ('AVP_SWIFTUI', 'AVP - SwiftUI'),
    ('AVP_UIKIT', 'AVP - UIKit'),
    ('AVP_UNITY_POLYSPATIAL', 'AVP - Unity PolySpatial'),
    ('BACKEND_API', 'Backend - API Design'),
    ('BACKEND_DATABASE', 'Backend - Database'),
    ('BLOCKCHAIN', 'Blockchain'),
    ('COGNITIVE3D', 'Cognitive3D'),
    ('DESIGN_3DS_MAX', 'Design - 3DS Max'),
    ('DESIGN_BLENDER', 'Design - Blender'),
    ('DESIGN_FIGMA', 'Design - Figma'),
    ('DESIGN_GIMP', 'Design - GIMP'),
    ('DESIGN_ILLUSTRATOR', 'Design - Illustrator'),
    ('DESIGN_MAYA', 'Design - Maya'),
    ('DESIGN_OTHER', 'Design - Other'),
    ('DESIGN_PHOTOSHOP', 'Design - Photoshop'),
    ('DESIGN_SHAPESXR', 'Design - ShapesXR'),
    ('FOUNDERS_LAB', 'Founders Lab'),
    ('GODOT_CSHARP', 'Godot - C# Script'),
    ('GODOT_GDSCRIPT', 'Godot - GDScript'),
    ('GODOT_OTHER', 'Godot - Other'),
    ('GODOT_SHADERS', 'Godot - Shaders'),
    ('HARDWARE_ARDUINO', 'Hardware - Arduino'),
    ('HARDWARE_ESP32', 'Hardware - Esp32'),
    ('HARDWARE_GPIO', 'Hardware - GPIO'),
    ('HARDWARE_RASPBERRY_PI', 'Hardware - Raspberry Pi'),
    ('HARDWARE_SENSORS', 'Hardware - Sensors'),
    ('LANG_JAVASCRIPT', 'Language - JavaScript'),
    ('LANG_CPP', 'Language - C and C++'),
    ('LANG_CSHARP', 'Language - C#'),
    ('LANG_JAVA', 'Language - Java'),
    ('LANG_OTHER', 'Language - Other'),
    ('LANG_PYTHON', 'Language - Python'),
    ('META_ANCHORS', 'Meta - Anchors'),
    ('META_AVATARS', 'Meta - Avatars'),
    ('META_DEVICES', 'Meta - Devices'),
    ('META_INTERACTIONS', 'Meta - Interactions'),
    ('META_MRUK', 'Meta - MRUK'),
    ('META_OTHER', 'Meta - Other'),
    ('META_SCENE', 'Meta - Scene'),
    ('MRTK', 'Mixed Reality Toolkit (MRTK)'),
    ('NETWORKING', 'Networking'),
    ('OS_ANDROID', 'OS - Android'),
    ('OS_IOS', 'OS - iOS'),
    ('OS_LINUX', 'OS - Linux Unix'),
    ('OS_MAC', 'OS - Mac'),
    ('OS_OTHER', 'OS - Other'),
    ('OS_WINDOWS', 'OS - Windows'),
    ('OTHER', 'Other'),
    ('PICO_DEVICES', 'PICO - Devices'),
    ('PICO_SDKS', 'PICO - SDKs'),
    ('PRESENTATION_OTHER', 'Presentation - Other'),
    ('PRESENTATION_PITCH', 'Presentation - Pitch'),
    ('PRESENTATION_RESEARCH', 'Presentation - Research'),
    ('PRESENTATION_STORYTELLING', 'Presentation - Storytelling'),
    ('PROJECT_ADVICE', 'Project - Advice'),
    ('PROJECT_MANAGEMENT', 'Project - Management'),
    ('PROJECT_OTHER', 'Project - Other'),
    ('PROJECT_SCOPE', 'Project - Scope'),
    ('QUALCOMM_DEVICES', 'Qualcomm - Devices'),
    ('QUALCOMM_ROBOTICS', 'Qualcomm - Robotics'),
    ('QUALCOMM_SDKS', 'Qualcomm - SDKs'),
    ('SNAP_AI', 'Snap - AI'),
    ('SNAP_LENS_STUDIO', 'Snap - Lens Studio'),
    ('SNAP_OTHER', 'Snap - Other'),
    ('SNAP_SPECTACLES', 'Snap - Spectacles'),
    ('SOURCE_CONTROL_CODEBERG', 'Source Control - Codeberg'),
    ('SOURCE_CONTROL_GIT', 'Source Control - Git'),
    ('SOURCE_CONTROL_OTHER', 'Source Control - Other'),
    ('STYLY', 'STYLY'),
    ('UNITY_ANIMATIONS', 'Unity - Animations'),
    ('UNITY_AR_FOUNDATION', 'Unity - AR Foundation'),
    ('UNITY_CSHARP', 'Unity - C# Scripting'),
    ('UNITY_OTHER', 'Unity - Other'),
    ('UNITY_SHADERS', 'Unity - Shaders'),
    ('UNITY_VISUAL_SCRIPTING', 'Unity - Visual Scripting'),
    ('UNITY_XRI', 'Unity - XRI'),
    ('UNREAL_ANIMATIONS', 'Unreal - Animations'),
    ('UNREAL_BLUEPRINTS', 'Unreal - Blueprints'),
    ('UNREAL_CPP', 'Unreal - C++'),
    ('UNREAL_OTHER', 'Unreal - Other'),
    ('UNREAL_SHADERS', 'Unreal - Shaders'),
    ('VIDEO_AFTER_EFFECTS', 'Video Editing - After Effects'),
    ('VIDEO_DAVINCI', 'Video Editing - DaVinci'),
    ('VIDEO_OTHER', 'Video Editing - Other'),
    ('VIDEO_PREMIERE', 'Video Editing - Premiere'),
    ('WEB_HTML', 'Web - HTML'),
    ('WEB_LIBRARIES', 'Web - Libraries'),
    ('WEB_OTHER', 'Web - Other'),
    ('WEBXR', 'WebXR')
]
